version: '3'
services:
  database:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
      # - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
  wordpress:
    depends_on:
      - database
    # image: wordpress:php7.0
    build: ./
    ports:
      - "8080:80"
    volumes:
      - ./public_html:/var/www/html:delegated
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini:ro
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    ports:
      - 8000:80
    volumes:
      - ./pma.ini:/usr/local/etc/php/conf.d/php.ini:ro
    environment:
      PMA_HOST: database
